spring:
  application:
    name:
      realtime-stock-analyzer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: stock-analyzer-new-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.bhanu.StockAnalyzer.dto.StockPrice

  datasource:
    url: jdbc:postgresql://localhost:5432/stockdb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata





server:
  port: 8080


kafka:
  topics:
    ticks: stock.ticks
    aggregates: stock.aggregates

# WebSocket prefix
app:
  websocket:
    endpoint: /ws-stock
    topic-prefix: /topic


redis:
  host: localhost
  port: 6379


streams:
  application-id: stock-streams-app
  bootstrap-servers: localhost:9092


